### PR TITLE
(wip) updated skin

### PR DESCRIPTION
**Pull request by eed3si9n**
Pending review
/cc @rasummer

### CODE REVIEW

**Comment by eed3si9n** [comment]
@rasummer Built it locally to check. LGTM.

**Comment by rasummer** [comment]
@eed3si9n I just realized that I should add a favicon to the site, let me do that before it's merged.

**Comment by eed3si9n** [comment]
Sure. Feel free to push things directly into wip/updated-skin.

**Comment by rasummer** [comment]
@eed3si9n added the favicon, ready to merge if you're happy with it.

**Comment by eed3si9n** [comment]
Merged. push to follow soon.

**Pull request merged**
