### PR TITLE
Fix Typo Mistake in Website.

### PR DESCRIPTION
**Pull request by ghisloine**
I've just noticed a typo mistake in the MD file.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ghisloine,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by ghisloine** [comment]
CLA signed

**Review by eed3si9n — APPROVED** [review]
Thanks, @ghisloine!

**Comment by ghisloine** [comment]
> Thanks, @ghisloine!

Anything to do for merge?

**Comment by eed3si9n** [comment]
Merged!

**Pull request merged**
