### PR TITLE
add zlib instructions for ubuntu

### PR DESCRIPTION
**Pull request by felher**
While trying to build the website on my machine, I stumbled into a problem with zlib. Since I'm using ubuntu, which I guess is pretty common, I thought it might be useful to add the fix to the readme.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by eed3si9n** [comment]
@felher Looks like the email used on your `git` is not tied to your GitHub account.

**Comment by felher** [comment]
I added my work email to my profile and verified it. I hope that fixes any problems this might have caused you. Sorry for that!

**Pull request merged**
