### PR TITLE
Emphasize that `%%` uses the binary Scala version

### PR DESCRIPTION
**Pull request by avdv**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Thanks!

**Comment by xuwei-k** [comment]
This changes are not enough https://github.com/sbt/website/issues/456

**Comment by dwijnand** [comment]
Sorry, Yoshida-san, why is this not enough?

If the concern is the olden days (2.9.x? early 2.10.x?) where the standard library wasn't binary compatible, then I think we needn't worry about that. IMO

**Comment by eed3si9n** [comment]
The suggested change in this PR is fine.

As per  #456, let's talk about it there.

**Pull request merged**
