### PR TITLE
Launcher related typos

### PR DESCRIPTION
**Pull request by leifwickland**
- Correct URL to launcher configuration.
- Correct path to local maven repo. I believe this is correct based on the behavior I see.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @leifwickland,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by leifwickland** [comment]
The error message I can see on Travis doesn't seem to indicate a problem why my PR, but I could be wrong. Please help me understand if i've made a mistake.
Thanks.

**Comment by eed3si9n** [comment]
You can ignore Travis on sbt/website. 
`~/.ivy2/cache/` is the Ivy cache, internal cache used by Ivy for all artifacts. It should not be used as a repository.
`~/.ivy2/local` is the Ivy local repository, where artifacts are published into with `publishLocal`.

**Comment by leifwickland** [comment]
@eed3si9n Thanks for explaining. Are your comments only directed at my inquiry about the possibility of the ivy location being wrong or also at my change to point maven to `~/.m2/repository`?
(I've removed the supposition about ivy's location from my comment to avoid confusion.)

I think I've jumped through the CLA hoops. Is the remainder of the PR a correct fix?

**Comment by eed3si9n** [comment]
I think your fixes are fine.

**Pull request merged**
