### PR TITLE
add sbt-scuggest plugin

### PR DESCRIPTION
**Pull request by ssanj**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ssanj,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ssanj** [comment]
Looks like the Travis build has stalled?

**Comment by eed3si9n** [comment]
Yea. Travis gets confused with PDF building I think.

**Comment by ssanj** [comment]
signed the CLA.

**Pull request merged**
