### PR TITLE
Add algolia search

### LINKED ISSUE #962: Join algolia's DocSearch program
I think SBT's docs are great but underappreciated - a search bar with instant response can go a long way in helping that.

I know that scala-lang.org is using https://docsearch.algolia.com/ (a free search program for significant open source projects). The PR to add it in is small: https://github.com/scala/docs.scala-lang/pull/1096/files

Creating this issue just to track, there are some actions:

1. A maintainer to request Algolia API key
2. Me to create a PR with HTML necessary for algolia to work

How does this sound?

### PR DESCRIPTION
**Pull request by keynmol**
Closes #962 

To Algolia's credit, adding this was 5 minutes of following instructions and a whole day of CSS. Mostly because `layout.html` didn't do anything for some reason, so I had to add and remove lots of custom css.

Plus there's duplication of `.st` pages. 

In the end I removed all the custom CSS and decided to make Algolia's base bootstrap theme to work properly first.

Outstanding:

- [x] @eed3si9n to apply for docsearch here: https://docsearch.algolia.com/docs/apply (sorry for picking on you Eugene, not sure what the full list of maintainers looks like :-)
       
     Given that API key is public, once there's one I'll be able to test this locally without having to merge :tada: 
- [ ] Some CSS tweaks to match the theme?
- [ ] Might be able to add language-localised to pages not in English, if it's worth it? I don't know how DocSearch's indexing works

Here's what it looks now with index pointing at scala-lang.org DocSearch

1. Reference pages 
image
2. Langing page
image

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @keynmol,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
For the record I did apply for DocSearch yesterday. Since it's Thanksgiving weekend, it might take a few days to process?

**Comment by keynmol** [comment]
Ah yes, you're right. Either way, the wheels are turning and SBT site should be at the top of priority list as it's open source :)

**Comment by eed3si9n** [comment]
Hello! I got the API key.

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: 'e47ee877a07ea1c48722f08430d54913',
indexName: 'scala-sbt',
inputSelector: '### REPLACE ME ####',
algoliaOptions: { 'facetFilters': ["lang:$LANG"] },
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

**Comment by eed3si9n** [comment]
And configuration is here - https://github.com/algolia/docsearch-configs/blob/master/configs/scala-sbt.json

**Comment by keynmol** [comment]
Yohoo! 

Let me update the PR and see what sort of results we get.

I can also push the locally generated version termporarily to http://surge.sh so that you can have a play around

**Comment by keynmol** [comment]
Perhaps the indexing hasn't happened yet - I've pushed the site with new configs here: http://scala-sbt.surge.sh/index.html

I can see requests going to algolia okay but the response doesn't contain any results.

I'll see if the regex in their sbt config is correct.

**Comment by keynmol** [comment]
A-ha, the regex is indeed incorrect. It collects **everything** after /docs into a `lang` facet filter.

Which means if I remove the facet filter the search should work.

**Comment by keynmol** [comment]
We're live! (I pushed the change to the the http://scala-sbt.surge.sh/1.x/docs/ as well)

image

But lack of facet does mean that visitors will learn a language or two :) 

image

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
