### PR TITLE
Add sbt-jupiter-interface to plugin list

### PR DESCRIPTION
**Pull request by maichler**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @maichler,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?website=pull/378/head&deploy_to_bintray=false">this link.</A>

**Comment by maichler** [comment]
Just signed the CLA.

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/79/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-1.0-1.0-1.0-1.0-pull/378/head)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/79/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@5f2e5cf10ef1a0fb73d149b46b71b1c5111f30a7
  zinc              | 1.0                  | sbt/zinc@26f11d213a4c4214e725d53be08e042e52e70692
  io                | 1.0                  | sbt/io@21ed6ec2a2e33fd88a5f013f643d04fda26de4de
  librarymanagement | 1.0                  | sbt/librarymanagement@f3c0eb2e5868f01b4e2610cb95321e2e9816e72f
  util              | 1.0                  | sbt/util@655d54d7c3d8a7231be867df09b40d1cffc83109
  website           | pull/378/head        | sbt/website@4d9c8d2b6e0b462b40db02ffe06d26a5a225c392

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=1.0&io=1.0&librarymanagement=1.0&util=1.0&website=pull/378/head&deploy_to_bintray=false">(restart)</A>

**Pull request merged**
