### PR TITLE
added unicredit/sbt-swagger-codegen

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @andreaTP,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by andreaTP** [comment]
I've done it for contributing to Scala.js

**Comment by eed3si9n** [comment]
Thanks!

**Comment by andreaTP** [comment]
Thanks to you @eed3si9n it is possible only due to your treehugger library :-)

Please, when you can find a slot check the code of the two places where I'm forced to do ugly ```String.replace``` to find an affordable solution with treehugger if possible.

**Pull request merged**
