### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Atulanand46**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Atulanand46,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by Atulanand46** [comment]
please accept

**Comment by mcsky** [comment]
@Atulanand46  do real contribution to OSS world to deserve your hacktoberfest t-shirt. Changing one word in a README is not playing the game, please read https://hacktoberfest.digitalocean.com/details/#spam.

Please, someone, mark this PR as spam and close it :)

**Comment by eed3si9n** [comment]
Hi Thanks for the interest into sbt/website. What made you and dozen others try to change sbt/web's README? Was this part of code camp or a school work?

**Comment by eed3si9n** [comment]
https://blog.domenic.me/hacktoberfest/

**Pull request closed without merging**
