### PR TITLE
Announce SBT 1.5.4

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Seems to have been forgotten after releasing https://github.com/sbt/sbt/releases/tag/v1.5.4 ?

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by eed3si9n** [comment]
I realized this didn't work because I didn't publish unidoc-scaladoc for sbt 1.5.4 yet and GitHub Pages failed - https://github.com/sbt/sbt.github.com/runs/2935402016

> The symbolic link `/1.x/api` targets a file which does not exist within your site's repository.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt.github.com/commit/a412bf01590cea0e621958cae9624b0a04289382.

**Pull request merged**
