### PR TITLE
Make example gender-neutral.

### PR DESCRIPTION
**Pull request by maasg**
Replaced unnecessary gender-specific references by neutral alternatives.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @maasg,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]
I think it's a The Big Lebowski reference, but I'd be happy to accept this change.

**Comment by maasg** [comment]
@eed3si9n do I need to sign the CLA as Lightbend employee?

**Comment by eed3si9n** [comment]
@maasg You probably don't have to, but please do to avoid the bot from reminding us for each PR.

**Comment by SethTisue** [comment]
(usually better to avoid these sorts of culturally-specific in-references too, actually)

**Pull request merged**
