### PR TITLE
Update 07C-Scope-Delegation.md

### PR DESCRIPTION
**Pull request by fistacuffs**
Fix typo in **Exercise E**.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @nickweitzel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by fistacuffs** [comment]
Signed the CLA

**Comment by eed3si9n** [comment]
Cool. Could you also fix the Japanese translation please? https://github.com/sbt/website/blob/develop/src/reference/ja/00-Getting-Started/07C-Scope-Delegation.md#value-%E5%8F%82%E7%85%A7-vs-%E5%8B%95%E7%9A%84%E3%83%87%E3%82%A3%E3%82%B9%E3%83%91%E3%83%83%E3%83%81
It currently says "projD/version は version in ThisBuild に委譲する。" but should follow your fix.

**Review by eed3si9n — APPROVED** [review]
Thanks @nickweitzel!

**Pull request merged**
