### PR TITLE
Add sbt-reactific plugin

### PR DESCRIPTION
**Pull request by reid-spencer**
This adds the autoplugin sbt-reactific to the "in-house plugins" section. sbt-reactific encapsulates all the sbt plugins and settings we use at Reactific to minimize project build clutter. It is our attempt to keep the sbt settings DRY. Others who want to use the same core set of plugins and features can get a jumpstart on configuring sbt with this plugin. This plugin will be upgraded to 1.0 support when its dependent plugins are.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]

**Comment by dwijnand** [comment]
Maybe this PR should target the 0.13 branch while it only exists for sbt 0.13?

**Comment by reid-spencer** [comment]
Do, I should just put this same doc change on the 0.13 branch?

I fully intend this to be a 1.0 plugin, I just can't yet as it depends on other plugins not upgraded yet. This plugin is how Reactific will move its software to 1.0

**Comment by dwijnand** [comment]
Whatever you prefer. We can leave this open until you have a release (although you run the risk of lots of merge conflicts as more plugins get added). And/or we can merge this doc change today in the 0.13 docs.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
> ### Plugins available for sbt 0.13 waiting for dependencies to upgrade to 1.0

hmm. This page should be just the list of sbt 1.x plugns.

**Comment by reid-spencer** [comment]
Dale says "whatever you prefer", Eugene wants changes, perhaps.  I'm happy to make any changes but would like to get this finalized, so let's all  get on the same page here. :)

The title you pondered is intended for 1.x plugins that cannot yet be upgraded to 1.x because their dependencies have not been upgraded. I'm working on upgrading them and submitting PRs to those projects. As soon as they are 1.x compliant, sbt-reactific will be too. Do you want that sort of project on the 1.x listing? I think it is useful to know which plugins are in the process of being converted to 1.x. Perhaps you do not? 

So, do you want:
A: The section removed from the 1.x branch?
B: The title changed on the 1.x branch? If so, to what?

**Comment by eed3si9n** [comment]
I am in agreement with the options that Dale presented:
1. Target to 0.13 branch if it's sbt 0.13 plugin, which you already did - https://github.com/sbt/website/pull/428
2. Or keep the PR open (and therefore unmerged) till sbt 1.x upgrade is completed.

> I think it is useful to know which plugins are in the process of being converted to 1.x. Perhaps you do not?

We are very much interested in the status of plugin migration status, so I've compiled the list here - https://github.com/sbt/sbt/wiki/sbt-1.x-plugin-migration. You're welcome to add yours.

**Comment by reid-spencer** [comment]
Okay, I removed the 1.x stuff and will add to the wiki. Thanks

**Comment by dwijnand** [comment]
Given this PR is a noop now, I'll close it. But, of course, feel free to add your plugin when it's released!

**Pull request closed without merging**
