### PR TITLE
Add note about migrating triggeredBy, runBefore

### PR DESCRIPTION
**Pull request by liff**

### CODE REVIEW

**Comment by liff** [comment]
Blocked by #1444 I guess.

**Comment by eed3si9n** [comment]
Could you actually mention sbt/sbt#1444 in this page?

**Comment by liff** [comment]
As in something like, _you'll still need to use `<<=` with `triggeredBy` and `runWith` due to sbt/sbt#1444_?

**Comment by eed3si9n** [comment]
Yea

**Comment by eed3si9n** [comment]
Thanks!

**Comment by dwijnand** [comment]
Thank you @liff

**Pull request merged**
