### PR TITLE
use Lightbend favicon and blue/orange color scheme

### PR DESCRIPTION
**Pull request by eed3si9n**
blue-orange

### CODE REVIEW

**Comment by dwijnand** [comment]
no wrench?

**Comment by eed3si9n** [comment]
@dwijnand now that we have _the_ wrench, I don't think we need any more.

**Comment by dwijnand** [comment]
what's _the_ wrench?

**Comment by eed3si9n** [comment]
The top-left logo will stay, but it doesn't render well as small size. See 

before

so I am using the Lightbend favicon:

favicon_screenshot

**Comment by dwijnand** [comment]
I don't think that's too bad. I think it would benefit if the background were transparent rather than white, like GitHub's favicon:
image

**Pull request merged**
