### PR TITLE
Add Safety-Plugin to community SBT Plugin page

### PR DESCRIPTION
**Pull request by leobenkel**
Link to the plugin: https://github.com/leobenkel/safety_plugin

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @leobenkel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]
Thanks @leobenkel!

**Comment by leobenkel** [comment]
@eed3si9n I think I have signed it. Right ? Or did I mess something up ? haha

**Comment by eed3si9n** [comment]
typesafe-cla-validator has green checkbox so it should be ok?

**Comment by leobenkel** [comment]
Cool Thanks !

**Comment by leobenkel** [comment]
How long does it take to be deploy to the live page ? 
https://www.scala-sbt.org/release/docs/Community-Plugins.html

**Pull request merged**
