### PR TITLE
Add sbt-no-publish

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Simple Plugin for disabling project publication. This keeps getting duplicated everywhere so making a plugin to turn it off made sense to me.

Just enable explicitly to turn off publishing. `.enablePlugin(NoPublishPlugin)

### CODE REVIEW

**Comment by eed3si9n** [comment]
Doesn't `publish / skip := true` work?

**Comment by ChristopherDavenport** [comment]
That may be the case, and this was then unnecessary(but I learned something valuable). All the builds I encounter generally set.

```
skip in publish := true,
publish := (()),
publishLocal := (()),
publishArtifact := false,
publishTo := None
```

If these are unnecessary. That's great! But there's a lack of information getting around the ecosystem effectively.

**Comment by eed3si9n** [comment]
Yea. Looks like it was one the features that shipped with sbt 1.0 but wasn't communicated well.

https://github.com/sbt/sbt/pull/3380

**Comment by ChristopherDavenport** [comment]
Great! Anywhere I was going to use this, I'll use that instead.

**Comment by ReoMaterSom** [comment]
#836

**Comment by eed3si9n** [comment]
I added documentation of skipping as part of https://github.com/sbt/website/pull/832

**Pull request closed without merging**
