### PR TITLE
Fix a link to sbt.Configuration docs in the Library Dependencies chapter...

### PR DESCRIPTION
**Pull request by admp**
....

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @admp,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by admp** [comment]
Apologies, but getting the contributors agreement approved by my employer feels like too much work to fix a single typo. Maybe next time.

**Comment by eed3si9n** [comment]
Sorry about this. You bring up a good point about the CLA process. I'm guessing that it's trying to say that if you are contributing code that was written during your work hours (at least in the United States) the copyright belongs to your employer, and therefore we cannot accept the code without explicit agreement by them. That said, the boundary of what you did as part of your employment vs what you did on your own, is much more blurry for programmers who are not paid by the hours or those who have signed employment agreement stating that everything you write around the clock belongs to them (apparently many employment agreements are framed exactly that way). I'll bring this up to internal discussion.

**Comment by eed3si9n** [comment]
Closing this via 1c4ced5

**Pull request closed without merging**
